modfileVersion: "v1"
id: github.com/SENERGY-Platform/mgw-device-command
name: Device Command
version: v2.2.0
type: add-on
deploymentType: single
license: "Apache License 2.0"
dependencies:
  github.com/SENERGY-Platform/mgw-device-repository-mirror-module:
    version: "<v2.0.0"
    requiredServices:
      device-repo-mirror:
        - refVar: DEVICE_REPOSITORY_URL
          template: "http://{ref}:8080"
          services:
            - device-command
  github.com/SENERGY-Platform/mgw-cloud-proxy/mgw-module:
    version: "<v1.0.0"
    requiredServices:
      gateway:
        - refVar: REQUEST_USER_IDP
          template: "mgw:http://{ref}:8080/api"
          services:
            - device-command
  github.com/SENERGY-Platform/mgw-mqtt-broker:
    version: <v2.0.0
    requiredServices:
      broker:
        - refVar: MGW_MQTT_BROKER
          template: "tcp://{ref}:1881"
          services:
            - device-command
  github.com/SENERGY-Platform/mgw-last-value-module:
    version: <v2.0.0
    requiredServices:
      mgw-last-value:
        - refVar: TIMESCALE_WRAPPER_URL
          template: "http://{ref}:8080"
          services:
            - device-command
services:
  device-command:
    name: device-command
    image: ghcr.io/senergy-platform/device-command:v1.0.42
    ports:
      - port: 8080
        hostPort: 8002
    httpEndpoints:
      - name: API
        extPath: "api"
        port: 8080
volumes:
  mgw-device-command:
    - mountPoint: /vol
      services:
        - device-command
configs:
  iotFallbackFile:
    dataType: string
    value: "/vol/devicerepo_fallback.json"
    targets:
      - refVar: IOT_FALLBACK_FILE
        services:
          - device-command
  useIotFallbackFile:
    dataType: string
    value: "true"
    targets:
      - refVar: USE_IOT_FALLBACK
        services:
          - device-command
  impl:
    dataType: string
    value: "mgw"
    targets:
      - refVar: TIMESCALE_IMPL
        services:
          - device-command
      - refVar: MARSHALLER_IMPL
        services:
          - device-command
      - refVar: COM_IMPL
        services:
          - device-command
  debug:
    dataType: string
    value: "false"
    options:
      - "true"
      - "false"
    optionsExt: false
    targets:
      - refVar: DEBUG
        services:
          - device-command
    userInput:
      type: text
      name: DEBUG