name: Validate

on:
  push:
    branches:
      - testing
      - main
  workflow_dispatch:

jobs:
  validate-modules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate
        run: docker run --rm --mount type=bind,src=./,dst=/mnt/data,ro ghcr.io/senergy-platform/mgw-module-validator:latest -m -d -blk .github,.git
      - name: Create Tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a ${{ github.ref_name }}-validated
          git push origin tag ${{ github.ref_name }}-validated --force
#      - name: Create commit file
#        run: echo ${{ github.sha }} > commit
#      - name: Release
#        uses: softprops/action-gh-release@v2
#        with:
#          name: ${{ github.ref_name }}
#          files: commit