name: Validate and tag

on:
  push:
    branches:
      - testing
      - main
  workflow_dispatch:

jobs:
  validate-modules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v4
      - name: Validate modules
        run: docker run --rm --mount type=bind,src=./,dst=/mnt/data,ro ghcr.io/senergy-platform/mgw-module-validator:latest -m -d -blk .github,.git
      - name: Create tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a ${{ github.ref_name }}-validated -m "validated commit ${{ github.sha }}"
          git push origin tag ${{ github.ref_name }}-validated --force